# Rhigh & Rlow model (Moscibrodzka+16)

## Check the data

In [2]:
from pyhamrds import bhoss
import os

#datadir = '/ccs/home/astrodoo/MEMW/BHOSS/BHOSS_CODE/outcomes/C3D2R512'
#data = 'GRRT_IMAGE_bhoss_data80.dat'

datadir = "/home/astrodoo/projects/rrg-dhaggard/astrodoo/EHT_bhoss/BHOSS_outcomes/bhoss_SA05"
data = "Rhigh_1_incl_10_IMAGE_GRMHD_HAMR3D_SANEA05_192_910.dat"

bhdata = bhoss.read_image(os.path.join(datadir,data),silent=False,ifreq=0)  # Koushik's data - only 230GHz

===================================== header ==================================
width: 20.134000 Rg, offset: 0.000000 Rg, resolution: 400, Number of obs. freqs: 1
time: 9101.943931 Rg/c, inclination: 10.000000 deg, phi: 0.000000 deg, BH spin: 0.500000
Luminosity correction: 4.762071e+22, Jansky correction: 6.025933e-01, Micro Arcsecond correction: 5.029644e+00
Frequencies of intereset [GHz]: [230.]
All-freq image is included (3rd column in image data): False
length of data: 480000
xmin: -101.266842, xmax: 101.266842, ymin: -101.266842, ymax: 101.266842
intensity (min,max)= 0.0 0.00039044
Total flux = 2.317690 Jy at 230 GHz


In [3]:
outdir = "/home/astrodoo/projects/rrg-dhaggard/astrodoo/EHT_bhoss/BHOSS_outcomes/bhoss2hdf5/bhoss_SA05"
bhdata.dump2hdf5(outdir=outdir,source='SgrA', Rhigh=1, Rlow=1, sigmacut=1, betacrit=1, \
                 normflux=2., tilt=0.,acc='SANE',silent=False)

convert the bhoss file to hdf5 format: /home/astrodoo/projects/rrg-dhaggard/astrodoo/EHT_bhoss/BHOSS_outcomes/bhoss2hdf5/bhoss_SA05/SgrA_SANE_a0.50_i010_Rh001_Rl01_sigc01_snorm2.0_t09101_f230GHz_np0400_fov101_tilt0.00.h5


In [4]:
bhoss.checkhdf5(os.path.join(outdir,"SgrA_SANE_a0.50_i010_Rh001_Rl01_sigc01_snorm2.0_t09101_f230GHz_np0400_fov101_tilt0.00.h5"))

/header/bh/acc SANE
/header/bh/dbh 2.5077305106e+22
/header/bh/fov 101
/header/bh/inc 10.0
/header/bh/mbh 8.234460000000001e+39
/header/bh/spin 0.5
/header/bh/tilt 0.0
/header/bh/time 9101.943931075635
/header/camera/dx 40.26800000003976
/header/camera/nx 400
/header/dsource 2.5077305106e+22
/header/emission/Rhigh 1
/header/emission/Rlow 1
/header/emission/betacrit 1
/header/emission/fov 101
/header/emission/janskycorr 0.6025932735218865
/header/emission/lumcorr 4.762071055774303e+22
/header/emission/microcorr 5.029643510174232
/header/emission/normflux 2.0
/header/emission/sigmacut 1
/header/freqcgs 230000000000.0
/header/scale 0.6025932735218865
/header/t 9101.943931075635
/header/units/L_unit 611495034824.0884
/header/units/T_unit 20.397278800925953
/unpol [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [5]:
import h5py
import numpy as np
import os

# file open
f = h5py.File(os.path.join(outdir,"SgrA_SANE_a0.50_i010_Rh001_Rl01_sigc01_snorm2.0_t09101_f230GHz_np0400_fov101_tilt0.00.h5"),"r")

In [6]:
dataset = f['unpol'][()]

In [9]:
print(dataset)
print(np.max(dataset),np.min(dataset))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
0.00039044 0.0


In [15]:
f.close()

## batch script for the file conversion

In [13]:
from pyhamrds import bhoss
import os
def bhoss2hdf5(Rhigh=1,Rlow=1,sig=1,inclination=0,model_name='',source='SgrA'):

    note=""
    if (model_name == "MADS41A5"):
        model_str = "bhoss_MA05"
        acc = 'MAD'
        ind_start = 311
        ind_end = 410
    elif (model_name == "MADS41A0"):
        model_str = "bhoss_MA0"
        acc = 'MAD'
        ind_start = 97
        ind_end = 196
    elif (model_name == "MADS41A93"):
        model_str = "bhoss_MA93"
        acc = 'MAD'
        ind_start = 96
        ind_end = 195
    elif (model_name == "MADS41A93M"):
        model_str = "bhoss_MA93M"
        acc = 'MAD'
        ind_start = 101
        ind_end = 200
    elif (model_name == "SANEA93M"):
        model_str = "bhoss_SA93M"
        acc = 'SANE'
        ind_start=132
        ind_end = 231
    elif (model_name == "SANEA93"):
        model_str = "bhoss_SA93"
        acc = 'SANE'
        ind_start=99
        ind_end = 198
    elif (model_name == "SANEA05"):
        model_str = "bhoss_SA05"
        acc = 'SANE'
        ind_start=900
        ind_end = 999
        note="192_"
    elif (model_name == "SANEA0"):
        model_str = "bhoss_SA0"
        acc = 'SANE'
        ind_start=640
        ind_end = 739
    else:
        print("no model")
        return
    
    basedir = "/home/astrodoo/projects/rrg-dhaggard/astrodoo/EHT_bhoss/BHOSS_outcomes"
    datadir = os.path.join(basedir,model_str)
    outdir = os.path.join(basedir,"bhoss2hdf5",model_str)
    
    #ind_start=400
    #ind_end=400
    for image_ind in range(ind_start,ind_end+1):
        print("%d out of %d"%(image_ind,ind_end))
        
        data_name="Rhigh_%d_incl_%d_IMAGE_GRMHD_HAMR3D_%s_%s%d.dat" \
                  %(Rhigh,inclination,model_name,note,image_ind)
        
        bhdata = bhoss.read_image(os.path.join(datadir,data_name),silent=True,ifreq=0)
        bhdata.dump2hdf5(outdir=outdir,source=source,Rhigh=Rhigh,Rlow=Rlow,sigmacut=sig,acc=acc, \
                         betacrit=1., normflux=2., tilt=0., silent=True)

In [16]:
bhoss2hdf5(model_name='SANEA05',Rhigh=1,inclination=10,Rlow=1,sig=1,source='SgrA')

900 out of 999
901 out of 999
902 out of 999
903 out of 999
904 out of 999
905 out of 999
906 out of 999
907 out of 999
908 out of 999
909 out of 999
910 out of 999
911 out of 999
912 out of 999
913 out of 999
914 out of 999
915 out of 999
916 out of 999
917 out of 999
918 out of 999
919 out of 999
920 out of 999
921 out of 999
922 out of 999
923 out of 999
924 out of 999
925 out of 999
926 out of 999
927 out of 999
928 out of 999
929 out of 999
930 out of 999
931 out of 999
932 out of 999
933 out of 999
934 out of 999
935 out of 999
936 out of 999
937 out of 999
938 out of 999
939 out of 999
940 out of 999
941 out of 999
942 out of 999
943 out of 999
944 out of 999
945 out of 999
946 out of 999
947 out of 999
948 out of 999
949 out of 999
950 out of 999
951 out of 999
952 out of 999
953 out of 999
954 out of 999
955 out of 999
956 out of 999
957 out of 999
958 out of 999
959 out of 999
960 out of 999
961 out of 999
962 out of 999
963 out of 999
964 out of 999
965 out of 999
966 out of

In [17]:
bhoss2hdf5(model_name='SANEA05',Rhigh=1,inclination=50,Rlow=1,sig=1,source='SgrA')

900 out of 999
901 out of 999
902 out of 999
903 out of 999
904 out of 999
905 out of 999
906 out of 999
907 out of 999
908 out of 999
909 out of 999
910 out of 999
911 out of 999
912 out of 999
913 out of 999
914 out of 999
915 out of 999
916 out of 999
917 out of 999
918 out of 999
919 out of 999
920 out of 999
921 out of 999
922 out of 999
923 out of 999
924 out of 999
925 out of 999
926 out of 999
927 out of 999
928 out of 999
929 out of 999
930 out of 999
931 out of 999
932 out of 999
933 out of 999
934 out of 999
935 out of 999
936 out of 999
937 out of 999
938 out of 999
939 out of 999
940 out of 999
941 out of 999
942 out of 999
943 out of 999
944 out of 999
945 out of 999
946 out of 999
947 out of 999
948 out of 999
949 out of 999
950 out of 999
951 out of 999
952 out of 999
953 out of 999
954 out of 999
955 out of 999
956 out of 999
957 out of 999
958 out of 999
959 out of 999
960 out of 999
961 out of 999
962 out of 999
963 out of 999
964 out of 999
965 out of 999
966 out of

In [18]:
bhoss2hdf5(model_name='SANEA05',Rhigh=1,inclination=90,Rlow=1,sig=1,source='SgrA')

900 out of 999
901 out of 999
902 out of 999
903 out of 999
904 out of 999
905 out of 999
906 out of 999
907 out of 999
908 out of 999
909 out of 999
910 out of 999
911 out of 999
912 out of 999
913 out of 999
914 out of 999
915 out of 999
916 out of 999
917 out of 999
918 out of 999
919 out of 999
920 out of 999
921 out of 999
922 out of 999
923 out of 999
924 out of 999
925 out of 999
926 out of 999
927 out of 999
928 out of 999
929 out of 999
930 out of 999
931 out of 999
932 out of 999
933 out of 999
934 out of 999
935 out of 999
936 out of 999
937 out of 999
938 out of 999
939 out of 999
940 out of 999
941 out of 999
942 out of 999
943 out of 999
944 out of 999
945 out of 999
946 out of 999
947 out of 999
948 out of 999
949 out of 999
950 out of 999
951 out of 999
952 out of 999
953 out of 999
954 out of 999
955 out of 999
956 out of 999
957 out of 999
958 out of 999
959 out of 999
960 out of 999
961 out of 999
962 out of 999
963 out of 999
964 out of 999
965 out of 999
966 out of

In [19]:
bhoss2hdf5(model_name='SANEA05',Rhigh=40,inclination=10,Rlow=1,sig=1,source='SgrA')

900 out of 999
901 out of 999
902 out of 999
903 out of 999
904 out of 999
905 out of 999
906 out of 999
907 out of 999
908 out of 999
909 out of 999
910 out of 999
911 out of 999
912 out of 999
913 out of 999
914 out of 999
915 out of 999
916 out of 999
917 out of 999
918 out of 999
919 out of 999
920 out of 999
921 out of 999
922 out of 999
923 out of 999
924 out of 999
925 out of 999
926 out of 999
927 out of 999
928 out of 999
929 out of 999
930 out of 999
931 out of 999
932 out of 999
933 out of 999
934 out of 999
935 out of 999
936 out of 999
937 out of 999
938 out of 999
939 out of 999
940 out of 999
941 out of 999
942 out of 999
943 out of 999
944 out of 999
945 out of 999
946 out of 999
947 out of 999
948 out of 999
949 out of 999
950 out of 999
951 out of 999
952 out of 999
953 out of 999
954 out of 999
955 out of 999
956 out of 999
957 out of 999
958 out of 999
959 out of 999
960 out of 999
961 out of 999
962 out of 999
963 out of 999
964 out of 999
965 out of 999
966 out of

In [20]:
bhoss2hdf5(model_name='SANEA05',Rhigh=40,inclination=50,Rlow=1,sig=1,source='SgrA')

900 out of 999
901 out of 999
902 out of 999
903 out of 999
904 out of 999
905 out of 999
906 out of 999
907 out of 999
908 out of 999
909 out of 999
910 out of 999
911 out of 999
912 out of 999
913 out of 999
914 out of 999
915 out of 999
916 out of 999
917 out of 999
918 out of 999
919 out of 999
920 out of 999
921 out of 999
922 out of 999
923 out of 999
924 out of 999
925 out of 999
926 out of 999
927 out of 999
928 out of 999
929 out of 999
930 out of 999
931 out of 999
932 out of 999
933 out of 999
934 out of 999
935 out of 999
936 out of 999
937 out of 999
938 out of 999
939 out of 999
940 out of 999
941 out of 999
942 out of 999
943 out of 999
944 out of 999
945 out of 999
946 out of 999
947 out of 999
948 out of 999
949 out of 999
950 out of 999
951 out of 999
952 out of 999
953 out of 999
954 out of 999
955 out of 999
956 out of 999
957 out of 999
958 out of 999
959 out of 999
960 out of 999
961 out of 999
962 out of 999
963 out of 999
964 out of 999
965 out of 999
966 out of

In [21]:
bhoss2hdf5(model_name='SANEA05',Rhigh=40,inclination=90,Rlow=1,sig=1,source='SgrA')

900 out of 999
901 out of 999
902 out of 999
903 out of 999
904 out of 999
905 out of 999
906 out of 999
907 out of 999
908 out of 999
909 out of 999
910 out of 999
911 out of 999
912 out of 999
913 out of 999
914 out of 999
915 out of 999
916 out of 999
917 out of 999
918 out of 999
919 out of 999
920 out of 999
921 out of 999
922 out of 999
923 out of 999
924 out of 999
925 out of 999
926 out of 999
927 out of 999
928 out of 999
929 out of 999
930 out of 999
931 out of 999
932 out of 999
933 out of 999
934 out of 999
935 out of 999
936 out of 999
937 out of 999
938 out of 999
939 out of 999
940 out of 999
941 out of 999
942 out of 999
943 out of 999
944 out of 999
945 out of 999
946 out of 999
947 out of 999
948 out of 999
949 out of 999
950 out of 999
951 out of 999
952 out of 999
953 out of 999
954 out of 999
955 out of 999
956 out of 999
957 out of 999
958 out of 999
959 out of 999
960 out of 999
961 out of 999
962 out of 999
963 out of 999
964 out of 999
965 out of 999
966 out of

In [22]:
bhoss2hdf5(model_name='SANEA05',Rhigh=160,inclination=10,Rlow=1,sig=1,source='SgrA')

900 out of 999
901 out of 999
902 out of 999
903 out of 999
904 out of 999
905 out of 999
906 out of 999
907 out of 999
908 out of 999
909 out of 999
910 out of 999
911 out of 999
912 out of 999
913 out of 999
914 out of 999
915 out of 999
916 out of 999
917 out of 999
918 out of 999
919 out of 999
920 out of 999
921 out of 999
922 out of 999
923 out of 999
924 out of 999
925 out of 999
926 out of 999
927 out of 999
928 out of 999
929 out of 999
930 out of 999
931 out of 999
932 out of 999
933 out of 999
934 out of 999
935 out of 999
936 out of 999
937 out of 999
938 out of 999
939 out of 999
940 out of 999
941 out of 999
942 out of 999
943 out of 999
944 out of 999
945 out of 999
946 out of 999
947 out of 999
948 out of 999
949 out of 999
950 out of 999
951 out of 999
952 out of 999
953 out of 999
954 out of 999
955 out of 999
956 out of 999
957 out of 999
958 out of 999
959 out of 999
960 out of 999
961 out of 999
962 out of 999
963 out of 999
964 out of 999
965 out of 999
966 out of

In [23]:
bhoss2hdf5(model_name='SANEA05',Rhigh=160,inclination=50,Rlow=1,sig=1,source='SgrA')

900 out of 999
901 out of 999
902 out of 999
903 out of 999
904 out of 999
905 out of 999
906 out of 999
907 out of 999
908 out of 999
909 out of 999
910 out of 999
911 out of 999
912 out of 999
913 out of 999
914 out of 999
915 out of 999
916 out of 999
917 out of 999
918 out of 999
919 out of 999
920 out of 999
921 out of 999
922 out of 999
923 out of 999
924 out of 999
925 out of 999
926 out of 999
927 out of 999
928 out of 999
929 out of 999
930 out of 999
931 out of 999
932 out of 999
933 out of 999
934 out of 999
935 out of 999
936 out of 999
937 out of 999
938 out of 999
939 out of 999
940 out of 999
941 out of 999
942 out of 999
943 out of 999
944 out of 999
945 out of 999
946 out of 999
947 out of 999
948 out of 999
949 out of 999
950 out of 999
951 out of 999
952 out of 999
953 out of 999
954 out of 999
955 out of 999
956 out of 999
957 out of 999
958 out of 999
959 out of 999
960 out of 999
961 out of 999
962 out of 999
963 out of 999
964 out of 999
965 out of 999
966 out of

In [24]:
bhoss2hdf5(model_name='SANEA05',Rhigh=160,inclination=90,Rlow=1,sig=1,source='SgrA')

900 out of 999
901 out of 999
902 out of 999
903 out of 999
904 out of 999
905 out of 999
906 out of 999
907 out of 999
908 out of 999
909 out of 999
910 out of 999
911 out of 999
912 out of 999
913 out of 999
914 out of 999
915 out of 999
916 out of 999
917 out of 999
918 out of 999
919 out of 999
920 out of 999
921 out of 999
922 out of 999
923 out of 999
924 out of 999
925 out of 999
926 out of 999
927 out of 999
928 out of 999
929 out of 999
930 out of 999
931 out of 999
932 out of 999
933 out of 999
934 out of 999
935 out of 999
936 out of 999
937 out of 999
938 out of 999
939 out of 999
940 out of 999
941 out of 999
942 out of 999
943 out of 999
944 out of 999
945 out of 999
946 out of 999
947 out of 999
948 out of 999
949 out of 999
950 out of 999
951 out of 999
952 out of 999
953 out of 999
954 out of 999
955 out of 999
956 out of 999
957 out of 999
958 out of 999
959 out of 999
960 out of 999
961 out of 999
962 out of 999
963 out of 999
964 out of 999
965 out of 999
966 out of

# Critical beta model (Anantua+20)

## Check the data

In [1]:
from pyhamrds import bhoss
import os

#datadir = '/ccs/home/astrodoo/MEMW/BHOSS/BHOSS_CODE/outcomes/C3D2R512'
#data = 'GRRT_IMAGE_bhoss_data80.dat'

datadir = "/home/astrodoo/projects/rrg-dhaggard/astrodoo/EHT_bhoss/BHOSS_outcomes/bhoss_SA05"
data = "f05_b1_incl_50_IMAGE_GRMHD_HAMR3D_SANEA05_192_910.dat"

bhdata = bhoss.read_image(os.path.join(datadir,data),silent=False,ifreq=2)  # Koushik's data - only 230GHz

===================================== header ==================================
width: 20.134000 Rg, offset: 0.000000 Rg, resolution: 400, Number of obs. freqs: 5
time: 9101.943931 Rg/c, inclination: 50.000000 deg, phi: 0.000000 deg, BH spin: 0.500000
Luminosity correction: 4.762071e+22, Jansky correction: 6.025933e-01, Micro Arcsecond correction: 5.029644e+00
Frequencies of intereset [GHz]: [  43.   86.  230.  345. 1360.]
All-freq image is included (3rd column in image data): False
length of data: 480000
xmin: -101.266842, xmax: 101.266842, ymin: -101.266842, ymax: 101.266842
intensity (min,max)= 0.0 0.00574402
Total flux = 2.132735 Jy at 230 GHz


In [2]:
outdir = "/home/astrodoo/projects/rrg-dhaggard/astrodoo/EHT_bhoss/BHOSS_outcomes/bhoss2hdf5/bhoss_SA05"
bhdata.dump2hdf5(outdir=outdir,source='SgrA', sigmacut=1, betacrit=1, f_ana=0.5, \
                 normflux=2., tilt=0.,acc='SANE',silent=False)

convert the bhoss file to hdf5 format: /home/astrodoo/projects/rrg-dhaggard/astrodoo/EHT_bhoss/BHOSS_outcomes/bhoss2hdf5/bhoss_SA05/SgrA_SANE_a0.50_i050_fa0.5_bc1.00_sigc01_snorm2.0_t09101_f230GHz_np0400_fov101_tilt0.00.h5


In [3]:
bhoss.checkhdf5(os.path.join(outdir,"SgrA_SANE_a0.50_i050_fa0.5_bc1.00_sigc01_snorm2.0_t09101_f230GHz_np0400_fov101_tilt0.00.h5"))

/header/bh/acc SANE
/header/bh/dbh 2.5077305106e+22
/header/bh/fov 101
/header/bh/inc 50.0
/header/bh/mbh 8.234460000000001e+39
/header/bh/spin 0.5
/header/bh/tilt 0.0
/header/bh/time 9101.943931075635
/header/camera/dx 40.26800000003976
/header/camera/nx 400
/header/dsource 2.5077305106e+22
/header/emission/betacrit 1
/header/emission/f_ana 0.5
/header/emission/fov 101
/header/emission/janskycorr 0.6025932735218865
/header/emission/lumcorr 4.762071055774303e+22
/header/emission/microcorr 5.029643510174232
/header/emission/normflux 2.0
/header/emission/sigmacut 1
/header/freqcgs 230000000000.0
/header/scale 0.6025932735218865
/header/t 9101.943931075635
/header/units/L_unit 611495034824.0884
/header/units/T_unit 20.397278800925953
/unpol [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


## batch script for the file conversion

In [8]:
from pyhamrds import bhoss
import os
def bhoss2hdf5(Te_model='f05_b1', sig=1,inclination=0,model_name='',source='SgrA'):

    note=""
    if (model_name == "MADS41A5"):
        model_str = "bhoss_MA05"
        acc = 'MAD'
        ind_start = 311
        ind_end = 410
    elif (model_name == "MADS41A0"):
        model_str = "bhoss_MA0"
        acc = 'MAD'
        ind_start = 97
        ind_end = 196
    elif (model_name == "MADS41A93M"):
        model_str = "bhoss_MA93M"
        acc = 'MAD'
        ind_start = 101
        ind_end = 200
    elif (model_name == "MADS41A93"):
        model_str = "bhoss_MA93"
        acc = 'MAD'
        ind_start = 96
        ind_end = 195
    elif (model_name == "SANEA93M"):
        model_str = "bhoss_SA93M"
        acc = 'SANE'
        ind_start=132
        ind_end = 231
    elif (model_name == "SANEA93"):
        model_str = "bhoss_SA93"
        acc = 'SANE'
        ind_start=99
        ind_end = 198
    elif (model_name == "SANEA05"):
        model_str = "bhoss_SA05"
        acc = 'SANE'
        ind_start=900
        ind_end = 999
        note="192_"
    else:
        print("no model")
        return
    
    if (Te_model=='f05_b1'):
        f_ana = 0.5
        betacrit=1.
    else:
        print('check the Te_model!!!')
        print("no model")
        return
    
    basedir = "/home/astrodoo/projects/rrg-dhaggard/astrodoo/EHT_bhoss/BHOSS_outcomes"
    datadir = os.path.join(basedir,model_str)
    outdir = os.path.join(basedir,"bhoss2hdf5",model_str)
    
    #ind_start=910
    #ind_end=910
    for image_ind in range(ind_start,ind_end+1):
        print("%d out of %d"%(image_ind,ind_end))
       
        data_name="%s_incl_%d_IMAGE_GRMHD_HAMR3D_%s_%s%d.dat" \
                  %(Te_model,inclination,model_name,note,image_ind)
        
        bhdata = bhoss.read_image(os.path.join(datadir,data_name),silent=True,ifreq=2)
        bhdata.dump2hdf5(outdir=outdir,source=source,sigmacut=sig,acc=acc, \
                         betacrit=betacrit, f_ana=f_ana, normflux=2., tilt=0., silent=True)

In [9]:
bhoss2hdf5(model_name='SANEA05',Te_model='f05_b1',inclination=10,sig=1,source='SgrA')

900 out of 999
901 out of 999
902 out of 999
903 out of 999
904 out of 999
905 out of 999
906 out of 999
907 out of 999
908 out of 999
909 out of 999
910 out of 999
911 out of 999
912 out of 999
913 out of 999
914 out of 999
915 out of 999
916 out of 999
917 out of 999
918 out of 999
919 out of 999
920 out of 999
921 out of 999
922 out of 999
923 out of 999
924 out of 999
925 out of 999
926 out of 999
927 out of 999
928 out of 999
929 out of 999
930 out of 999
931 out of 999
932 out of 999
933 out of 999
934 out of 999
935 out of 999
936 out of 999
937 out of 999
938 out of 999
939 out of 999
940 out of 999
941 out of 999
942 out of 999
943 out of 999
944 out of 999
945 out of 999
946 out of 999
947 out of 999
948 out of 999
949 out of 999
950 out of 999
951 out of 999
952 out of 999
953 out of 999
954 out of 999
955 out of 999
956 out of 999
957 out of 999
958 out of 999
959 out of 999
960 out of 999
961 out of 999
962 out of 999
963 out of 999
964 out of 999
965 out of 999
966 out of

In [10]:
bhoss2hdf5(model_name='SANEA05',Te_model='f05_b1',inclination=50,sig=1,source='SgrA')

900 out of 999
901 out of 999
902 out of 999
903 out of 999
904 out of 999
905 out of 999
906 out of 999
907 out of 999
908 out of 999
909 out of 999
910 out of 999
911 out of 999
912 out of 999
913 out of 999
914 out of 999
915 out of 999
916 out of 999
917 out of 999
918 out of 999
919 out of 999
920 out of 999
921 out of 999
922 out of 999
923 out of 999
924 out of 999
925 out of 999
926 out of 999
927 out of 999
928 out of 999
929 out of 999
930 out of 999
931 out of 999
932 out of 999
933 out of 999
934 out of 999
935 out of 999
936 out of 999
937 out of 999
938 out of 999
939 out of 999
940 out of 999
941 out of 999
942 out of 999
943 out of 999
944 out of 999
945 out of 999
946 out of 999
947 out of 999
948 out of 999
949 out of 999
950 out of 999
951 out of 999
952 out of 999
953 out of 999
954 out of 999
955 out of 999
956 out of 999
957 out of 999
958 out of 999
959 out of 999
960 out of 999
961 out of 999
962 out of 999
963 out of 999
964 out of 999
965 out of 999
966 out of

In [11]:
bhoss2hdf5(model_name='SANEA05',Te_model='f05_b1',inclination=90,sig=1,source='SgrA')

900 out of 999
901 out of 999
902 out of 999
903 out of 999
904 out of 999
905 out of 999
906 out of 999
907 out of 999
908 out of 999
909 out of 999
910 out of 999
911 out of 999
912 out of 999
913 out of 999
914 out of 999
915 out of 999
916 out of 999
917 out of 999
918 out of 999
919 out of 999
920 out of 999
921 out of 999
922 out of 999
923 out of 999
924 out of 999
925 out of 999
926 out of 999
927 out of 999
928 out of 999
929 out of 999
930 out of 999
931 out of 999
932 out of 999
933 out of 999
934 out of 999
935 out of 999
936 out of 999
937 out of 999
938 out of 999
939 out of 999
940 out of 999
941 out of 999
942 out of 999
943 out of 999
944 out of 999
945 out of 999
946 out of 999
947 out of 999
948 out of 999
949 out of 999
950 out of 999
951 out of 999
952 out of 999
953 out of 999
954 out of 999
955 out of 999
956 out of 999
957 out of 999
958 out of 999
959 out of 999
960 out of 999
961 out of 999
962 out of 999
963 out of 999
964 out of 999
965 out of 999
966 out of